
server:
  port: 8082
  servlet:
    context-path: /conb
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic
